### PR TITLE
Fixes

### LINKED ISSUE #102: Add support for object rules?
Right now, Validator automatically deeply flattens every object, so its impossible to test a value that happens to be an object.

For example, this is the rule I want to validate:

``` js
// input
{
  foo: {
    isTested: false,
    isValid: false,
    isDone: false
  }
}

// rule
{
  foo: 'singleTrueRule'
}

// registered rule
Validator.register('singleTrueRule', value => {
  return Object.keys(value).some(k => k.value === true);
});
```

Any plans to support object rules?

### PR DESCRIPTION
**Pull request by LKay**
- remove flattenings input object
- add extracting value by path,
- add test for `Date` instance

Fixes #102, #104

### CODE REVIEW

File: src/validator.js [hunk 1]
```diff
@@ -177,6 +177,37 @@ Validator.prototype = {
...
+   */
+  _objectPath: function (obj, path) {
+    if (obj.hasOwnProperty(path)) {
+      return obj[path];
+    }
+    
+    var keys = path.replace(/\[(\w+)\]/g, ".$1").replace(/^\./, "").split(".");
+    var copy = obj.constructor();
+
+    for (var attr in obj) {
```
Comment (bricejlin) [inline src/validator.js:194]: Why not use `Object.assign` here to copy the object? Or at least use a polyfill to support IE?

**Comment by bricejlin** [comment]
Thanks for putting in this fix! It looks good to me

File: src/validator.js (hunk 1 above)
Comment (LKay) [inline src/validator.js:194]: Just to be compatible with ES5 and current version of the library as it doesn't use any externals. If @skaterdav85 wishes then I can easily replace this whole method with `object-path` lib. That would also apply to flattening method as it can be replaced by `flat`.

Comment (bricejlin) [inline src/validator.js:194]: Got it. I guess that's for a separate discussion / PR. This looks fine at it is then!

**Comment by bricejlin** [comment]
can we get a release published with this fix please?

**Comment by iamdtang** [comment]
@bricejlin released in 3.1.1
